name: Code check
on:
  push:

jobs:
  build:
    name: Build package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9.7

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.1.13
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Cache venv
        uses: actions/cache@v2
        with:
          path: |
            .venv
          key: ${{ runner.os }}-env-${{ hashFiles('**/poetry.lock') }}

      - name: Set up environment
        run: poetry install --no-root

      - name: Linting
        run: |
          source $PWD/.venv/bin/activate
          black --check src
          pylint src

      - name: Step 1 - Create a temporary artifact folder
        run: mkdir artifacts

      - name: step 2 - Add artifacts to publish to the temp folder
        run: |
          source $PWD/.venv/bin/activate
          echo $PATH
          ./install.sh
          mv fb_scraper.exe artifacts/fb_scraper.exe

      - name: Step 3 - Use the Upload Artifact GitHub Action
        uses: actions/upload-artifact@v2
        with:
          name: fb_scraper_app
          path: artifacts
